# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG=github.com/the42/cartconvert
GOFILES=\
	cartconvert.go\

# gb: this is the local install
GBROOT=.

# gb: compile/link against local install
GC+= -I $(GBROOT)/_obj
LD+= -L $(GBROOT)/_obj

package: $(GBROOT)/_obj/$(TARG).a

include $(GOROOT)/src/Make.pkg

